version: '2'
services:
 MariaDB:
  image: mariadb:1.0.0
  hostname: mariadb
  container_name: mariadb
  privileged: true
  volumes:
   - pgvolume:/var/lib/mysql
   - ./my.cnf:/etc/mysql/my.cnf
  expose:
   - "22"
   - "3306"
  ports:
   - "127.0.0.1:2200:22"
   - "3306:3306"
volumes:
 pgvolume:
  external:
   name: MariaDB
